package org.agripmu.cropverification.util

import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.Context
import android.os.Build
import androidx.core.app.NotificationCompat
import androidx.work.Worker
import androidx.work.WorkerParameters
import org.agripmu.cropverification.R

class MyWorker(context: Context, workerParams: WorkerParameters) : Worker(context, workerParams) {
    override fun doWork(): Result {
      createLocalNotification("Background Notification for Crop Verification app "
      ,"This notification is generated by workManager")

        return  Result.success()
    }

    private fun createLocalNotification(title : String, description : String){

        val notificationManager = applicationContext.getSystemService(Context.NOTIFICATION_SERVICE)
        as NotificationManager
         if(Build.VERSION.SDK_INT  >= Build.VERSION_CODES.O){
             val notificationChannel = NotificationChannel("101","channel"
                 ,NotificationManager.IMPORTANCE_DEFAULT)

             notificationManager.createNotificationChannel(notificationChannel)
         }

        val notificationBuilder = NotificationCompat.Builder(applicationContext,"101")
            .setContentTitle(title)
            .setContentText(description)
            .setSmallIcon(R.drawable.agri_main_logo)

        notificationManager.notify(1,notificationBuilder.build())

    }
}